imports:
    - { resource: tables.yml }
services:
    dmzx.walletindex.admin.controller:
        class: dmzx\walletindex\controller\admin_controller
        arguments:
            - '@config'
            - '@template'
            - '@log'
            - '@user'
            - '@dbal.conn'
            - '@request'
            - '@config_text'
            - '%tables.walletindex_table%'
            - '%tables.walletindex_currency_table%'
            - '@ext.manager'
            - '@path_helper'
    dmzx.walletindex.wallet.controller:
        class: dmzx\walletindex\controller\wallet_controller
        arguments:
            - '@template'
            - '@user'
            - '@dbal.conn'
            - '@config'
            - '@controller.helper'
            - '@config_text'
            - '%tables.walletindex_table%'
            - '%tables.walletindex_currency_table%'
            - '@ext.manager'
            - '@path_helper'
    dmzx.walletindex.listener:
        class: dmzx\walletindex\event\listener
        arguments:
            - '@template'
            - '@user'
            - '@dbal.conn'
            - '@config'
            - '@controller.helper'
            - '%tables.walletindex_table%'
            - '%core.php_ext%'
            - '@ext.manager'
            - '@path_helper'
        tags:
            - { name: event.listener }
